### ISSUE TITLE
Suggestion: use compressed keys for significantly shorter redemption scripts

### ISSUE THREAD

**Issue by theStack** [GlacierProtocol/GlacierProtocol#1]
While analyzing the _redemption script_ output of the Glacier python script creating multisig deposit data (parameter `create-deposit-data`), I saw that the pushed public keys have a size of 65 bytes. Obviously the old uncompressed public key format is used, resulting in quite large redemption scripts. Is there any specific reason for using this? (Backwards compatibility for old clients or the like?) With compressed keys, a public key in the redemption script would only be 33 bytes of size.

The change would be as simple as to add one byte during the WIF key creation process in function ```hex_private_key_to_WIF_private_key()```, see https://en.bitcoin.it/wiki/Wallet_import_format ("2 - Add a 0x80 byte in front of it for mainnet addresses or 0xef for testnet addresses. **Also add a 0x01 byte at the end if the private key will correspond to a compressed public key**"). In line 223, ```hex_key_with_prefix = "80" + hex_key + "01"``` will do the trick. bitcoind will recognize the resulting private key string as _WIF compressed_ format and accordingly create compressed public keys.

For users of the Glacier protocol, this change would have two advantages:
- significantly shorter redemption scripts => almost 50% less to type in for the withdrawal process (if the electronic copy of the _Cold Storage Information Page_ is lost)
- correspondingly shorter withdrawal transaction size => less fees to pay

Only drawback: the WIF private keys are slightly longer (52 instead of 51 characters). Also, they start with either 'K' or 'L' instead of '5'.

Example redemption script analysis for a 2-of-4 multisignature policy:
Uncompressed: OP_2 Push65[...] Push65[...] Push65[...] Push65[...] OP_4 OP_CHECKMULTISIG (length: **267 bytes**)
Compressed: OP_2 Push33[...] Push33[...] Push33[...] Push33[...] OP_4 OP_CHECKMULTISIG (length: **139 bytes**)

**Comment by jhogan4288** [comment]
Thanks.  This makes sense to me.  I don't think there's any reason we used uncompressed keys (unless Jacob corrects me below); it was probably just an oversight.

Have you executed the entire Glacier deposit protocol and withdrawal protocol with keys generated using this method?  And if so, did it work *precisely* as described (i.e. without requiring any tweaks or corrections on your part)  That'd be my only other concern -- if something else in the protocol (for example, some of the Bitcoin Core RPC calls which GlacierScript does) is currently expecting an uncompressed key in particular.

@jacoblyles, any comments / corrections?

**Comment by bitcoinhodler** [comment]
I request prioritizing this fix. I had to pay a $35 transaction fee for a simple withdrawal the other day. Anything that can reduce the transaction size would be welcome.

(I realize that after this fix I'll have to create a new cold storage address and move my bitcoins to that new address before I can take advantage.)

**Comment by bitcoinhodler** [comment]
This was released in v0.93.
