### ISSUE TITLE
Suggest different blockchain monitoring tool

### ISSUE THREAD

**Issue by gracenoah** [GlacierProtocol/GlacierProtocol#30]
It appears that Blockr has been shut down ([article here](https://www.ccn.com/blockr-io-shuttered-by-coinbase/)).  Glacier should suggest using a different tool to monitor transactions, like https://blockchain.info/

**Comment by jlopp** [comment]
I'd recommend either blockstream.info or running our own version of it (Esplora). The former would be a faster fix for sure.
