### ISSUE TITLE
Suggesting that the best way for newbies to hold BTC is without owning the private keys

### ISSUE THREAD

**Issue by jazarija** [GlacierProtocol/GlacierProtocol#41]
The chapter "Self-Managed Storage vs. Online" reads

> For most people, most of the time, the authors recommend storing Bitcoin using a high-quality
> online storage service. The pros and cons of the various online services are beyond the scope of this
> document, but most popular ones are fairly secure and easy to use. Some popular options are
> Blockchain (https://blockchain.info/), Coinbase (https://www.coinbase.com/), Gemini (https://
> gemini.com/), and Kraken (https://www.kraken.com/).

I'd argue that it's not good to encourage people not to own their private keys, let alone keep them on  blockchain.info. 

Therefore, I'd suggest rewriting the above along the lines of

> While it might be convenient to store bitcoin in an online wallet, there are many security concerns due to fact that the user is not in full control of his private keys. Users should at least consider using a hardware wallet such as <X>,<Y>, <Z>.

**Comment by bitcoinhodler** [comment]
NACK. The very next paragraph lists out all the risks of online storage, and the section after that talks about hardware wallets. While there are security concerns with online storage, there are also (different) security concerns with holding one's own private keys, even with a hardware wallet.
