### ISSUE TITLE
Issues with 0.93 Release

### ISSUE THREAD

**Issue by aurumbarr** [GlacierProtocol/GlacierProtocol#43]
In the 0.93 release I found the zbarcam app wasn't available and bitcoind wouldn't start (timeout error).

**Comment by aurumbarr** [comment]
You're right, thanks.  After shutting down the quarantined computers (as instructed) it's necessary to again go through the following steps when restarting them to do the test withdrawal:
_Install the application software on the Q1 computer’s RAM disk.
 $ cd ~/apps
 $ sudo dpkg -i *.deb

Change into the glacier directory. You’ll be using this directory to execute software for the protocol.
 $ cd ~/glacier

Prepare GlacierScript for execution.
$ chmod +x glacierscript.py_

**Comment by bitcoinhodler** [comment]
The test withdrawal step says to execute the Withdrawal Protocol, and step 5.2.1 says to execute Section VI of the Setup Protocol to prepare the quarantined workspace.

As of Glacier v0.93, there is no "Section VI" but there is a 3.6 titled "Prepare Quarantined Workspaces" that includes the steps which @aurumbarr missed above.

Aside from the erroneous section reference, I don't see any issue with the doc. That section reference should get cleaned up as part of the work being done to [convert to Asciidoc](https://github.com/GlacierProtocol/glacierprotocol.github.io/issues/13).

**Comment by aurumbarr** [comment]
Thanks - really appreciate the comments.
