### ISSUE TITLE
Issue when running 'create-withdrawal-data'

### ISSUE THREAD

**Issue by aurumbarr** [GlacierProtocol/GlacierProtocol#44]
When running the 'create-withdrawal-data' process, I am seeing an error "Transaction data not found for source address" after inputting the "raw unsigned transaction" in hexadecimal format.  Having checked the "raw unsigned transaction" input several times, I believe it is accurate.

Any assistance with possible reasons for this would be much appreciated.

**Comment by bitcoinhodler** [comment]
This message occurs when the raw transaction has been successfully decoded as a bitcoin transaction, but your cold storage address was not found in that tx's outputs.

It would be a big help if you could give us details on the transaction, but for your privacy, you shouldn't do that. Instead I'll tell you how to do some legwork yourself to pinpoint the issue.

Go to https://coinb.in/#verify and paste in the raw transaction. I tried this with a recent randomly-chosen transaction from the blockchain just now. Look at the addresses listed under the "Outputs" section.

Do you see your cold storage address in that list?

**Comment by aurumbarr** [comment]
Thanks.  Confirmed I do see the correct cold storage address.  I had actually checked with a couple of different block explorers, which also both showed the correct cold storage address.  So it seems all's in order in that regard.

**Comment by bitcoinhodler** [comment]
Disturbing...do you have access to an instance of Bitcoin Core 0.17.0 where you can run `decoderawtransaction`? In the output JSON you should see tx["vout"][N]["scriptPubKey"]["addresses"] and for some N your address ought to be in there. For example here's a recent transaction I picked randomly, as output by `decoderawtransaction`:

```
{
  "txid": "d7b1bef7a06f9ecf4ec3bcb21a9a94ba29d4a3de03140cdb62d539d281f5ed82",
  "hash": "d7b1bef7a06f9ecf4ec3bcb21a9a94ba29d4a3de03140cdb62d539d281f5ed82",
  "version": 1,
  "size": 222,
  "vsize": 222,
  "weight": 888,
  "locktime": 0,
  "vin": [
    {
      "txid": "8e57e654fb6f834b8b965800aa8450af5f4160ab9c14b6c08195e7c1b4da19c3",
      "vout": 48,
      "scriptSig": {
        "asm": "3045022100ccde32e915f54a2ef223321c06f26ee54b297501dfee74c6af2a1b49b823e67a02200c4ef6a66fd1a6498a1fb6ba37076387ae342a316c6fa98096adc7d809e00bf4[ALL] 034e0ee4ae47fd179c8b2918bf89c51cc811c10693ebcbc1197a33440db7419643",
        "hex": "483045022100ccde32e915f54a2ef223321c06f26ee54b297501dfee74c6af2a1b49b823e67a02200c4ef6a66fd1a6498a1fb6ba37076387ae342a316c6fa98096adc7d809e00bf40121034e0ee4ae47fd179c8b2918bf89c51cc811c10693ebcbc1197a33440db7419643"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.03935628,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_HASH160 30897cc6c9d69f6a2c2f1c651d51f22219f1a4f6 OP_EQUAL",
        "hex": "a91430897cc6c9d69f6a2c2f1c651d51f22219f1a4f687",
        "reqSigs": 1,
        "type": "scripthash",
        "addresses": [
          "367f4YWz1VCFaqBqwbTrzwi2b1h2U3w1AF"
        ]
      }
    },
    {
      "value": 0.20000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_HASH160 a5f890ef97b07cf2bdf5b26371138f79d09e2d9d OP_EQUAL",
        "hex": "a914a5f890ef97b07cf2bdf5b26371138f79d09e2d9d87",
        "reqSigs": 1,
        "type": "scripthash",
        "addresses": [
          "3GpbBshxKV9uHDhDp8CKYEksbDyfFVHGtR"
        ]
      }
    }
  ]
}
```

This tx has two outputs, to addresses 367f4YWz1VCFaqBqwbTrzwi2b1h2U3w1AF and 3GpbBshxKV9uHDhDp8CKYEksbDyfFVHGtR.

If this doesn't explain the problem, the next step is I'll have you edit GlacierScript to add some debug printouts during execution so you can better pinpoint the issue.

**Comment by aurumbarr** [comment]
I do... and have been trying to run decoderawtransaction on that but unfort. having some issues with that too.  As an alternative, would "http://chainquery.com/bitcoin-api/decoderawtransaction" suffice?  If so, the vout does include the correct address.  

I wanted to also ask, might I have made a mistake when running create-withdrawal-data in saying I wanted to use only one unspent transaction output?  Perhaps there were two or more?  How might I know?  (I could of course re-run create-withdrawal-data and input '2', '3', 'etc' and see if that worked?)

Thanks..

**Comment by bitcoinhodler** [comment]
The number you give to GlacierScript is the number of transactions, not the number of outputs. It scans through all outputs of each transaction you paste, so it should have found this vout.

I have to guess there's something silly going on here...GlacierScript is not this broken. Are you sure the cold storage address as given to GlacierScript is correct?

If you're willing to hack on the Python code, you can add some print statements to the function `get_utxos` to give you some clues as to what's going on. Print out tx, address, and (inside the for loop) the out_addresses.

**Comment by aurumbarr** [comment]
Okay so I ran 'create-withdrawal-data' on the laptop which runs my full node and it seemed to work fine - I successfully reached the point at which the user is prompted to enter private keys.  So perhaps there's something amiss with my Apps USB and I should recreate it?

I also ran 'decoderawtransation' on my quarantined laptop, and after I started 'bitcoind -daemon' this worked fine with the relevant 'raw unspent transaction' - I could see in the 'vout' information the correct amount of BTC and the correct cold storage address.

In terms of adding some print statements to the glacierscript.py code, I found that 'hex_tx' returned the correct 'raw unspent transaction' however 'tx' returned '[ ]'.  Perhaps for some reason I'm having an issue getting suitable output from "tx = json.loads(subprocess.check_output(bitcoin_cli + "decoderawtransaction {0}".format(hex_tx), shell=True))"?  Is there a separate step I might need to complete to get bitcoind running, such that 'decoderawtransaction' will run when 'create-withdrawal-data' is run?  I understood bitcoind is started as part of glacierscript.py, but pls correct me if that's wrong.

V happy to print out anything else you might see as helpful.  Thanks as always..!

**Comment by bitcoinhodler** [comment]
Very strange; `ensure_bitcoind_running` has already run and tested that `bitcoin-cli` is working properly. I'm running out of ideas.

I'd suggest printing out the output of `decoderawtransaction` directly, before it's passed to `json.loads`.

Before change (line 690 of `glacierscript.py`):
```
    tx = json.loads(subprocess.check_output(bitcoin_cli + "decoderawtransaction {0}".format(hex_tx), shell=True))
```

After:
```
    raw_out = subprocess.check_output(bitcoin_cli + "decoderawtransaction {0}".format(hex_tx), shell=True)
    print raw_out
    tx = json.loads(raw_out)
```

**Comment by aurumbarr** [comment]
Ok thanks, I've made that change to glacierscript.py and have the 'raw_out'.  It looks very similar to the example decoderawtransaction you posted above.  Is there any particular output/s you'd like me to share to assist in the diagnosis?

**Comment by bitcoinhodler** [comment]
OK, that's good -- but then how did tx end up as [] inside `get_utxos`? Something's fishy there. And it appears to me that if tx were indeed [] then `get_utxos` would bomb out with an error message on line 333 when it tried to access `tx["vout"]` since there would be no key named "vout". So let's go back to `get_utxos` like I suggested above:

> If you're willing to hack on the Python code, you can add some print statements to the function get_utxos to give you some clues as to what's going on. Print out tx, address, and (inside the for loop) the out_addresses.

Whatever's happening here, I want to figure it out and (at the very least) add some kind of sanity check to GlacierScript to catch this problem cleanly.

**Comment by aurumbarr** [comment]
Tks, I have the tx, address, out_address printouts from the get_utxos function.... what can I usefully share with you?  (Also to let you know I also recreated another Apps USB, got the same result unfort.).

**Comment by bitcoinhodler** [comment]
Verify that the list of out_addresses matches the expected list (the addresses of each output in the tx), and that the address is still your expected cold storage address, and that one of them matches one of the out_address.

I really think there's something silly like an extra carriage return in the string, or an extra space before the address, or something like that, and that's why it's not matching. Double-check that there's nothing like that.

**Comment by bitcoinhodler** [comment]
Find me on gitter.im if you want to share your private transaction details for more debug help.

**Comment by aurumbarr** [comment]
Issue now resolved - back-tracing steps, the cold storage address used to generate the QR code for the withdrawal transaction (but oddly not for the deposit transaction) had one letter as lowercase which should have been uppercase.  Unsure how this happened, was pasted in MS Word so perhaps autocorrect(?).  Notwithstanding, the Protocol clearly states to check the address.

**Comment by bitcoinhodler** [comment]
Perhaps there's still an improvement to be made here...in the case of this error, we could have GlacierScript print out the addresses that it did find, and explain what it was looking for. That would have made the debug of this issue a lot easier, and I suspect you won't be the last person to make a typo in the address.
