### ISSUE TITLE
Source of OS entropy 

### ISSUE THREAD

**Issue by jazarija** [GlacierProtocol/GlacierProtocol#47]
Currently it seems that Glacier sources its entropy by directly reading _/dev/random_. I wonder if that's the best way.

First of all the manapge of /dev/random reads

> Unless you are doing long-term key generation (and most likely not even then), you probably shouldn't be reading from the /dev/random device 

Which is also confirmed by this article: [myths about urandom.](https://www.2uo.de/myths-about-urandom/) 

Finally, Python's cryptography package seem to be recommending the same approach, see https://cryptography.io/en/latest/random-numbers/ 

As well as [this]( https://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/ ) article where it says

> **Doesn’t the man page say to use /dev/random?**
> 
> Don’t use /dev/random. The distinction between /dev/random and /dev/urandom is a Unix design wart. The man page doesn’t want to admit that, so it invents a security concern that doesn’t really exist. Consider the cryptographic advice in random(4) an urban legend and get on with your life.

Note also that bitcoin core seem to be using urandom as well, see [here](https://github.com/bitcoin/bitcoin/blob/bccb4d29a8080bf1ecda1fc235415a11d903a680/src/random.cpp).

So I wonder

**Does it makes sense to simplify the code and just use os.urandom?** 

At the very least it would make the whole code slightly more simple, since we'd directly rely on Python's random wrapper instead of calling external Unix programs. 

This is a sensitive question and I yet I waned to raise this issue here since any kind of simplification counts IMO.

**Comment by jazarija** [comment]
After closer inspection, it seems like bitcoin core is using OpenSSL's random function, which is relying on many sources of entropy as I understand it.

I wonder if it makes sense to use that one.

**Comment by bitcoinhodler** [comment]
I read some of your links and learned way more than I ever wanted to know about RNG. A few points:

* Simplification is good, but change is expensive.
* The Myths page accepts that there's nothing wrong with using /dev/random for long-term key generation (which is what we're doing).
* At the bottom of the Myths page is a discussion of too-little entropy at startup. This is the situation with Glacier when we boot the quarantined laptop as a fresh system. It's possible that urandom won't have enough entropy collected when we try to use it.

My conclusion: let's leave it as-is.

Though I certainly appreciate your efforts and discussion.

**Comment by jazarija** [comment]
Agree, I am mostly raising this issues to make sure all aspects of the protocol are healthy.

I will create a short, isolated function generating a private key as Glacier currently does and ask some experts around if there is anything sensitive about it. If not then I totally agree its best not to change the current code.

**Comment by jazarija** [comment]
Here is gmaxwell's take on it 

> < gmaxwell> I don't think that is a particullarly great construction, it looks pretty fragile to me. But it also looks like it probably (shrugs) works.
> < gmaxwell> well I'd worry that for example, the steps cause the subprocess call to fail with high probablity due to subtle interactions, etc.  Python has standard calls to get crypto randomness.
>  < gmaxwell> That have things like error handling.
> < gmaxwell> Which this code lacks completely, so if anything goes wrong, god knows what you get.
> < gmaxwell> Because this two lines of python with no effort at handling the obviously possible errors, surely handles things better than os.random...
> < gmaxwell> I wouldn't be qualified to make a good recommendation for python, but subprocessing out to run xxd with no error handling is almost certantly not it.

About the error checking, I am assuming subprocess, as actually being called should cause no harm.
 
Though I tend to agree that it would be better to rely as much as possible on built in functions as possible. If nothing else it reduces our dependency on external programs. For example, I just noticed that on icecube xxd is missing and hence needs to be installed as an additional package for otherwise glacier fails producing the entropy.

**Comment by bitcoinhodler** [comment]
I don't think the lack of error handling, in this case, is an issue. The computer entropy generated by this process gets printed to the screen for manual copying by the user. If something goes wrong, it will be obvious to the user. There's no chance of bad (or zero) entropy data getting used to generate a key, for example.

**Comment by jazarija** [comment]
Yes I agree, the error handler is not an issue. 

I'd say that its a bit unconventional and ad hoc as is, but I've done my homework about this part and I'll sleep fine if this is left as is :-) 

Closing this down now.
