### ISSUE TITLE
Should exchanges be proposed for secure storage?

### ISSUE THREAD

**Issue by tkalfigo** [GlacierProtocol/GlacierProtocol#67]
Page 5/78 of the text says:

> For most people, most of the time, the authors recommend storing Bitcoin using a high-quality
online storage service. The pros and cons of the various online services are beyond the scope of this document, but most popular ones are fairly secure and easy to use. Some popular options are Blockchain (https://blockchain.info/), Coinbase (https://www.coinbase.com/), Gemini (https://
gemini.com/), and Kraken (https://www.kraken.com/).

Despite the warning following this paragraph, should it be suggested they are a solution? Rationale against it:

1. The proposed services are not custodial services. And even the ones (e.g. Coinbase) that explicitly have a custodial service, are only for institutions, which I don't think is the target group of this document.

1. This potentially reduces the document's credibility as it might be considered to constitute paid advertising.

1. The exchanges themselves advise ["do not store more coins on an exchange than you need to actively trade"](https://twitter.com/jespow/status/1085348666699739141?lang=en).

**Comment by jazarija** [comment]
It seems that your issue is either very much related or a duplicate of this one https://github.com/GlacierProtocol/GlacierProtocol/issues/41

**Comment by tkalfigo** [comment]
@jazarija Agreed, it is. The document tries to fix things later on, but this still doesn't justify the existence of this paragraph. It leaves the reader with the impression that it is (even remotely) a good suggestion storing funds long term in exchanges. I'll close it as duplicate. I think the maintainer understands the point and will change the text accordingly.
