### ISSUE TITLE
Fix tests to work against Bitcoin Core 0.18

### ISSUE THREAD

**Issue by jlopp** [GlacierProtocol/GlacierProtocol#71]
Somewhat related to https://github.com/GlacierProtocol/GlacierProtocol/issues/38

Any given version of the protocol should state what version of Core it is tested against and compatible with.

**Comment by bitcoinhodler** [comment]
Can you elaborate on the problem you're seeing? GlacierScript and the developer tests have been compatible with 0.18 since #50, and I've run the tests on v0.18 many times myself, including just now.

**Comment by jlopp** [comment]
I was getting a 'method not found' error for getaddressesbylabel; maybe the bitcoin-cli was older than the bitcoind version

**Comment by bitcoinhodler** [comment]
Very strange; `getaddressesbylabel` was added in v0.17, and GlacierScript does a version check using `getnetworkinfo` to ensure you have at least v0.17. I guess that only checks `bitcoind` and not `bitcoin-cli`?

Do you think we should add a version check of  `bitcoin-cli` also? This condition is not something we would ever see on the quarantined laptops.

**Comment by jlopp** [comment]
I wouldn't worry about it; I updated both of my binaries to 0.18.1 and the tests pass
